### ISSUE TITLE
The assembly mscorlib.dll was not found or could not be loaded.

### ISSUE THREAD

**Issue by fatalaa** [friism/heroku-buildpack-mono#12]
Hi,
I am trying to host a console app on Heroku, it's based on Nancy's self hosted method.

Deploy succeeds, but here are the heroku logs:
`2015-04-27T15:25:37.326779+00:00 heroku[web.1]: Starting process with command mono Poker-Player-CSharp/bin/Debug/Poker-Player-CSharp.exe`

`2015-04-27T15:25:39.589867+00:00 app[web.1]: It should have been installed in the /app/mono/lib/mono/2.0/mscorlib.dll' directory.`

`2015-04-27T15:25:39.589853+00:00 app[web.1]: The assembly mscorlib.dll was not found or could not be loaded.`

`2015-04-27T15:25:40.407050+00:00 heroku[web.1]: State changed from starting to crashed`

Thanks in advance

**Comment by friism** [comment]
Hey, I think it might be because there's no .NET 2.0 profile, but you can run `heroku run bash -a {youapp}` to look around.

Here's the Mono build script: https://github.com/friism/mono-builder/blob/master/cedar-14/build

**Comment by fatalaa** [comment]
And how to use this?

**Comment by fatalaa** [comment]
If you just simply provide a guide about how to make it up and running from scratch, that would be great. Thanks in advance.

**Comment by friism** [comment]
This has build instructions: https://github.com/friism/mono-builder

You then have to fork the buildpack and use a different mono: https://github.com/friism/heroku-buildpack-mono/blob/master/bin/compile#L7

**Comment by fatalaa** [comment]
Thanks, solved it

**Comment by friism** [comment]
Awesome!

Consider taking a look at what the Suave guys did, that's F# too so maybe you can re-use: https://github.com/SuaveIO/mono-script-buildpack
